<a href="https://colab.research.google.com/github/Jaehooni/2022_Summer_D.Com_DeepLearning_Study/blob/main/lab06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Imports**

In [14]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

**Softmax**
$$ P(class=i) = \frac{e^i}{\sum e^i} $$

In [15]:
z = torch.FloatTensor([1, 2, 3])

In [16]:
hypothesis = F.softmax(z, dim=0)
print(hypothesis)

tensor([0.0900, 0.2447, 0.6652])


In [17]:
hypothesis.sum()

tensor(1.)

**Cross Entropy Loss**
$$ L = \frac{1}{N} \sum - y \log(\hat{y}) $$
<br>
두개의 확률 분포가 주어졌을 때 두 확률 분포의 유사성을 체크
<br>
활용: Cross Entropy를 minimize하는 방식으로 모델 최적화

**Cross Entropy Loss (Low-level)**

In [18]:
z = torch.rand(3, 5, requires_grad=True)
hypothesis = F.softmax(z, dim=1)
print(hypothesis)

tensor([[0.1586, 0.2454, 0.1100, 0.2147, 0.2712],
        [0.2083, 0.2200, 0.1940, 0.1907, 0.1870],
        [0.2361, 0.2674, 0.1744, 0.2034, 0.1187]], grad_fn=<SoftmaxBackward0>)


In [19]:
y = torch.randint(5, (3,)).long()
print(y)

tensor([4, 0, 4])


In [20]:
y_one_hot = torch.zeros_like(hypothesis)
y_one_hot.scatter_(1, y.unsqueeze(1), 1)

tensor([[0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1.]])

In [21]:
cost = (y_one_hot * -torch.log(hypothesis)).sum(dim=1).mean()
print(cost)

tensor(1.6682, grad_fn=<MeanBackward0>)


**Cross-entropy Loss with torch.nn.functional**

<small> PyTorch has `F.log_softmax()` function </small>

In [22]:
# Low level
torch.log(F.softmax(z, dim=1))

tensor([[-1.8411, -1.4048, -2.2069, -1.5385, -1.3050],
        [-1.5687, -1.5143, -1.6399, -1.6570, -1.6767],
        [-1.4436, -1.3189, -1.7466, -1.5925, -2.1311]], grad_fn=<LogBackward0>)

In [23]:
# High level
F.log_softmax(z, dim=1)

tensor([[-1.8411, -1.4048, -2.2069, -1.5385, -1.3050],
        [-1.5687, -1.5143, -1.6399, -1.6570, -1.6767],
        [-1.4436, -1.3189, -1.7466, -1.5925, -2.1311]],
       grad_fn=<LogSoftmaxBackward0>)

<small> PyTorch also has `F.nll_loss()` function that computes the negative loss likelihood. </small>

In [24]:
# Low level
(y_one_hot * -torch.log(F.softmax(z, dim=1))).sum(dim=1).mean()

tensor(1.6682, grad_fn=<MeanBackward0>)

In [25]:
# High level
F.nll_loss(F.log_softmax(z, dim=1), y)
#NLL = Negative Log Likelihood

tensor(1.6682, grad_fn=<NllLossBackward0>)

In [26]:
F.cross_entropy(z, y)

tensor(1.6682, grad_fn=<NllLossBackward0>)

<small> PyTorch also has `F.cross_entropy` that combines `F.log_softmax()` and `F.nll_loss()`. </small>